{{- $secrets :=  readFile "./secrets.yaml" | fromYaml -}}

helmfiles:
  - ../k8s/helmfile.defaults.yaml

helmDefaults:
  kubeContext: glados

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.11.0
    values:
      - installCRDs: true

  - name: cluster-issuers
    chart: ../k8s/charts/cluster-issuers
    namespace: cert-manager
    values:
      - {{- $secrets.cluster_issuers | toYaml | nindent 8}}

  - name: huisheng
    chart: huisheng/huisheng
    namespace: huisheng
    values:
      - ./values/huisheng.yaml
      - {{- $secrets.huisheng | toYaml | nindent 8 }}

  - name: metrics-server
    chart: metrics-server/metrics-server
    namespace: kube-system
    version: 3.8.4
    values:
      - ./values/metrics-server.yaml

  - chart: traefik/traefik
    name: traefik
    namespace: kube-system
    version: 21.2.0
    values:
      - ./values/traefik.yaml
