---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-credentials
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels: {}
data:
  {{- range $name, $solver := .Values.solvers }}
  {{ $name }}_hosted_zone_id: {{ $solver.hostedZoneID | b64enc }}
  {{ $name }}_access_key_id: {{ $solver.accessKeyID | b64enc }}
  {{ $name }}_secret_access_key: {{ $solver.secretAccessKey | b64enc }}
  {{- end }}
