---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-credentials
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels: {}
data:
  {{- range $name, $solver := .Values.solvers }}
  {{- if $solver.secretAccessKey }}
  {{ $name }}_secret_access_key: {{ $solver.secretAccessKey | b64enc }}
  {{- end }}
  {{- end }}
