runners:
  - organization: axatol
    maxReplicas: 3
    minReplicas: 0
    authorizedNamespaces:
      - actions-runners
      - home-assistant
      - jayd

  - repository: hans-m-song/blog
    maxReplicas: 3
    minReplicas: 0

  - repository: hans-m-song/huisheng
    maxReplicas: 3
    minReplicas: 0
    authorizedNamespaces:
      - huisheng

  - repository: hans-m-song/iac
    maxReplicas: 3
    minReplicas: 0

shared:
  env:
    DISABLE_RUNNER_UPDATE: "true"
    GOPATH: /home/runner/.cache/go
    GOMODCACHE: /home/runner/.cache/go/pkg/mod
    npm_config_cache: /home/runner/.cache/npm
    YARN_CACHE_FOLDER: /home/runner/.cache/yarn

  volumes:
    tool-cache:
      mountPath: /opt/hostedtoolcache
      config:
        persistentVolumeClaim:
          claimName: tool-cache
    module-cache:
      mountPath: /home/runner/.cache
      config:
        persistentVolumeClaim:
          claimName: module-cache
