runners:
  - organization: axatol
    max_replicas: 3
    min_replicas: 0
    node_selectors:
      axatol.xyz/supports-nfs: "true"
    authorized_namespaces:
      - actions-runners
      - home-assistant
      - jayd

  - repository: hans-m-song/blog
    max_replicas: 3
    min_replicas: 0
    node_selectors:
      axatol.xyz/supports-nfs: "true"

  - repository: hans-m-song/huisheng
    max_replicas: 3
    min_replicas: 0
    node_selectors:
      axatol.xyz/supports-nfs: "true"
    authorized_namespaces:
      - huisheng

  - repository: hans-m-song/iac
    max_replicas: 3
    min_replicas: 0
    node_selectors:
      axatol.xyz/supports-nfs: "true"

shared:
  env:
    DISABLE_RUNNER_UPDATE: "true"
    GOPATH: /home/runner/.cache/go
    GOMODCACHE: /home/runner/.cache/go/pkg/mod
    npm_config_cache: /home/runner/.cache/npm
    YARN_CACHE_FOLDER: /home/runner/.cache/yarn

  volumes:
    tool-cache:
      mountPath: /opt/hostedtoolcache
      config:
        persistentVolumeClaim:
          claimName: arc-tool-cache-pvc
    module-cache:
      mountPath: /home/runner/.cache
      config:
        persistentVolumeClaim:
          claimName: arc-module-cache-pvc
