logLevel: info
logFormat: json

policy: sync
registry: noop
interval: 1h
triggerLoopOnEvent: true

provider: pihole
sources: [ingress]
domainFilters: [axatol.local]

env:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: external-dns-pihole
        key: EXTERNAL_DNS_PIHOLE_PASSWORD

extraArgs:
  # - --dry-run
  # - --annotation-filter=external-dns.alpha.kubernetes.io/hostname
  - --pihole-server=http://192.168.1.41
  - --default-targets=192.168.1.42
