loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2024-12-22
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    # retention_period: 672h # 28 days retention
  # storage_config:
  # aws:
  # bucketnames: loki-chunks
  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      rules: loki-rules
      admin: loki-admin

test:
  enabled: false

lokiCanary:
  enabled: false

resultsCache:
  enabled: false

chunksCache:
  enabled: false

gateway:
  enabled: true
  verboseLogging: false # TODO change?
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: loki.axatol.xyz
      external-dns.alpha.kubernetes.io/target: http://loki-gateway.monitoring.svc.cluster.local:80

# resultsCache:
#   enabled: false
# chunksCache:
#   enabled: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: nfs-persistent
    size: 5Gi

# SimpleScalable
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

# Distributed
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
