persistence:
  storageClass: nfs-persistent

ingress:
  ingressClass: traefik
  apiHost: api.minio.k8s.axatol.xyz
  consoleHost: minio.k8s.axatol.xyz
  tls:
    - secretName: minio-k8s-axatol-xyz-tls
      hosts:
        - minio.k8s.axatol.xyz
    - secretName: api-minio-k8s-axatol-xyz-tls
      hosts:
        - api.minio.k8s.axatol.xyz
