containers:
  minio:
    image: quay.io/minio/minio:latest
    args: ["server", "/data", "--console-address", ":9001"]
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
    volumes:
      data:
        mount:
          mountPath: /data
          readOnly: false
        spec:
          persistentVolumeClaim:
            claimName: data
    ports:
      console:
        protocol: TCP
        internalPort: 9001
        externalPort: 9001
      api:
        protocol: TCP
        internalPort: 9000
        externalPort: 9000

ingress:
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer-prd
  hosts:
    minio.k8s.axatol.xyz:
      - path: /
        portName: console
        tls: true
    api.minio.k8s.axatol.xyz:
      - path: /
        portName: api
        tls: true

pvc:
  data:
    storageClassName: nfs-persistent
    capacity: 1Gi
