containers:
  minio:
    image: quay.io/minio/minio:latest
    args:
      - server
      - /data
      - --console-address
      - :9001
    resources:
      limits:
        cpu: 400m
        memory: 2Gi
    volumes:
      data:
        mount:
          mountPath: /data
          readOnly: false
        spec:
          persistentVolumeClaim:
            claimName: data
    ports:
      console:
        protocol: TCP
        internalPort: 9001
        externalPort: 9001
      api:
        protocol: TCP
        internalPort: 9000
        externalPort: 9000
        metricsEndpoints:
          - path: /minio/v2/metrics/cluster
          - path: /minio/v2/metrics/bucket

ingress:
  ingressClassName: traefik
  hosts:
    minio.axatol.local:
      - path: /
        portName: console
    api.minio.axatol.local:
      - path: /
        portName: api
    minio.axatol.xyz:
      - path: /
        portName: console

pvc:
  data:
    storageClassName: nfs-persistent
    capacity: 1Gi
