containers:
  mongo:
    image: mongo:latest
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
    volumes:
      data:
        mount:
          mountPath: /data/db
          readOnly: false
        spec:
          persistentVolumeClaim:
            claimName: data
    ports:
      mongo:
        protocol: TCP
        internalPort: 27017
        externalPort: 27017
    livenessProbe:
      tcpSocket:
        port: 27017
      initialDelaySeconds: 10

pvc:
  data:
    storageClassName: nfs-persistent
    capacity: 1Gi
