raw:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: nfs-persistent
      namespace: kube-system
    provisioner: cluster.local/nfs-subdir-external-provisioner
    allowVolumeExpansion: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    parameters:
      archiveOnDelete: "false"
      onDelete: retain
      pathPattern: ${.PVC.namespace}/${.PVC.name}
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: nfs-ephemeral
    provisioner: cluster.local/nfs-subdir-external-provisioner
    allowVolumeExpansion: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    parameters:
      archiveOnDelete: "false"
      onDelete: delete
      pathPattern: ${.PVC.namespace}/${.PVC.name}
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: nfs
    provisioner: nfs.csi.k8s.io
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    parameters:
      mountPermissions: "0"
      server: 192.168.1.42
      share: /mnt/data/nfs/k8s
      subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
    mountOptions:
      - nfsvers=4.1
      - hard
