octopus:
  acceptEula: "Y"
  image:
    tag: 2023.4

  packageRepositoryVolume:
    size: 1Gi
  artifactVolume:
    size: 1Gi
  taskLogVolume:
    size: 1Gi
  ingress:
    enabled: false
    # annotations:
    #   kubernetes.io/ingress.class: traefik
    # path: /
    # hosts:
    #   - octopus.k8s.axatol.xyz
