octopus:
  acceptEula: "Y"
  image:
    tag: 2023.4

  serverLogVolume:
    storageClassName: nfs-persistent
  packageRepositoryVolume:
    storageClassName: nfs-persistent
  artifactVolume:
    storageClassName: nfs-persistent
  taskLogVolume:
    storageClassName: nfs-persistent
  ingress:
    enabled: true
    className: traefik
    hosts:
      - octopus.k8s.axatol.xyz
