octopus:
  acceptEula: "Y"

  serverLogVolume:
    storageClassName: nfs-persistent
  packageRepositoryVolume:
    storageClassName: nfs-persistent
  artifactVolume:
    storageClassName: nfs-persistent
  taskLogVolume:
    storageClassName: nfs-persistent
  ingress:
    enabled: true
    className: traefik
    annotations:
      # cert-manager.io/cluster-issuer: cluster-issuer-prd
      # external-dns.alpha.kubernetes.io/hostname: octopus.axatol.xyz
      # exteranl-dns.alpha.kubernetes.io/target: axatol.xyz
    # tls:
    #   - hosts:
    #       - octopus.axatol.local
    # #     secretName: octopus-k8s-axatol-xyz-tls
    hosts:
      - octopus.axatol.local
