octopus:
  acceptEula: "Y"

  serverLogVolume:
    storageClassName: nfs-persistent
  packageRepositoryVolume:
    storageClassName: nfs-persistent
  artifactVolume:
    storageClassName: nfs-persistent
  taskLogVolume:
    storageClassName: nfs-persistent
  ingress:
    enabled: true
    className: traefik
    annotations:
      external-dns.alpha.kubernetes.io/hostname: octopus.axatol.local
    hosts:
      - octopus.axatol.local
