crds:
  enabled: true

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-persistent
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alertmanager.axatol.local

grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - grafana.axatol.local
  persistence:
    enabled: true
    type: sts
    storageClassName: nfs-persistent
    accessModes:
      - ReadWriteOnce
    size: 5Gi
  additionalDataSources:
    - name: Loki
      url: http://loki-gateway.monitoring.svc.cluster.local

prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.axatol.local
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-persistent
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
