crds:
  enabled: true

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-persistent
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alertmanager.monitoring.axatol.local

grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - grafana.monitoring.axatol.local
  persistence:
    enabled: true
    type: sts
    storageClassName: nfs-persistent
    accessModes:
      - ReadWriteOnce
    size: 5Gi
  additionalDataSources:
    - name: Loki
      url: http://loki-gateway.monitoring.svc.cluster.local

prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.monitoring.axatol.local
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-persistent
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
    additionalScrapeConfigs:
      - job_name: kubernetes_pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            action: keep
            regex: true
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels:
              - __meta_kubernetes_namespace
            action: replace
            target_label: namespace
          - source_labels:
              - __meta_kubernetes_pod_name
            action: replace
            target_label: pod_name
