prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: kubernetes_pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            action: keep
            regex: "true"
          - source_labels:
              - __meta_kubernetes_pod_phase
            action: drop
            regex: Succeeded|Failed
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
            action: replace
            target_label: __metrics_path__
            regex: (.+)
            replacement: $1
          - source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels:
              - __meta_kubernetes_namespace
            action: replace
            target_label: namespace
          - source_labels:
              - __meta_kubernetes_pod_name
            action: replace
            target_label: pod
          - source_labels:
              - __meta_kubernetes_pod_container_name
            action: replace
            target_label: container
          - source_labels:
              - __meta_kubernetes_pod_node_name
            action: replace
            target_label: node
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
            action: replace
            target_label: app_name
