containers:
  redis-insight:
    image: redislabs/redisinsight:latest
    resources:
      limits:
        cpu: 400m
        memory: 512Mi
    ports:
      http:
        protocol: TCP
        internalPort: 8001
        externalPort: 8001
    readinessProbe:
      httpGet:
        path: /
        port: 8001
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 10
    volumes:
      db:
        mount:
          mountPath: /db
          readOnly: false
        spec:
          emptyDir: {}

ingress:
  ingressClassName: traefik
  hosts:
    redis.axatol.local:
      - path: /
        portName: http
