---
- name: Configure containers
  hosts: atlas
  become: true
  gather_facts: true
  vars_prompt:
    - name: ansible_sudo_pass
      prompt: Sudo password
      private: true
  tasks:
    - name: Deploy atlas docker compose stack
      ansible.builtin.import_role:
        name: docker_compose_stack
      vars:
        docker_compose_stack_project: atlas
        docker_compose_stack_src: "{{ playbook_dir }}/files"
        docker_compose_stack_restart_map:
          otelcol-config.yaml: otel-collector
          custom.conf: pihole
