---
- name: Pull images
  hosts: atlas.local
  tasks:
    - name: Pull images
      community.docker.docker_image_pull:
        name: "{{ item }}"
      with_items:
        - traefik:latest
        - portainer/portainer-ce:latest
        - adguard/adguardhome:latest
        - qmcgaw/gluetun:latest
