{{- $secrets :=  readFile "./secrets.yaml" | fromYaml -}}

helmfiles:
  - ../k8s/helmfile.defaults.yaml

helmDefaults:
  kubeContext: wheatley

releases:
  - name: actions-runner-controller
    chart: actions-runner-controller/actions-runner-controller
    namespace: actions-runner-system
    version: 0.23.0
    values:
      - githubWebhookServer:
          enabled: true
      - {{ $secrets.actions_runner_controller | toYaml | nindent 8 }}

  - name: actions-runners
    chart: ../k8s/charts/actions-runners
    namespace: actions-runner-system
    values:
      - ./values/actions-runners.yaml

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.11.0

  - name: cluster-issuer
    chart: ../k8s/charts/cluster-issuers
    namespace: cert-manager
    values:
      - {{- $secrets.cluster_issuers | toYaml | nindent 8 }}

  - name: custom
    chart: ./custom

  - name: huisheng
    chart: huisheng/huisheng
    namespace: huisheng
    values:
      - ./values/huisheng.yaml
      - {{- $secrets.huisheng | toYaml | nindent 8 }}

  - name: metrics-server
    chart: metrics-server/metrics-server
    namespace: kube-system
    version: 3.8.4
    values:
      - ./values/metrics-server.yaml

  - name: nri-bundle
    chart: newrelic/nri-bundle
    namespace: newrelic
    version: 5.0.25
    values:
      - ./values/nri-bundle.yaml
      - {{ $secrets.newrelic | toYaml | nindent 8 }}

  - name: nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    namespace: kube-system
    version: 4.0.18
    values:
      - ./values/nfs-subdir-external-provisioner.yaml

  - name: octopus-deploy
    chart: oci://registry-1.docker.io/octopusdeploy/octopusdeploy-helm
    namespace: octopus
    version: 2023.2.12482
    values:
      - ./values/octopus-deploy.yaml
      - {{- $secrets.octopus | toYaml | nindent 8 }}

  - name: octopus-deploy-mssql
    chart: ../k8s/charts/mssql
    namespace: octopus
    values:
      - {{- $secrets.octopus_mssql | toYaml | nindent 8 }}

  - name: octopus-deploy-worker
    chart: ../k8s/charts/octopus-deploy-worker
    namespace: octopus
    values:
      - {{- $secrets.octopus_deploy_worker | toYaml | nindent 8 }}

  - name: redis
    chart: oci://registry-1.docker.io/bitnamicharts/redis
    namespace: redis
    version: 17.15.3
    values:
      - architecture: standalone
      - {{- $secrets.redis | toYaml | nindent 8}}

  - name: redis-insight
    chart: ../k8s/charts/redis-insight
    namespace: redis
    values:
      - ./values/redis-insight.yaml
      
  - chart: traefik/traefik
    name: traefik
    namespace: kube-system
    version: 21.2.0
    values:
      - ./values/traefik.yaml
