{{- $secrets :=  readFile "./secrets.yaml" | fromYaml -}}

helmfiles:
  - ../k8s/helmfile.defaults.yaml

helmDefaults:
  kubeContext: wheatley

releases:
  - name: actions-runner-controller
    chart: actions-runner-controller/actions-runner-controller
    namespace: actions-runner-system
    version: 0.23.0
    values:
      - githubWebhookServer:
          enabled: true
      - {{ $secrets.actions_runner_controller | toYaml | nindent 8 }}

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.11.0

  - name: metrics-server
    chart: metrics-server/metrics-server
    namespace: kube-system
    version: 3.8.4
    values:
      - ./values/metrics-server.yaml

  - name: nri-bundle
    chart: newrelic/nri-bundle
    namespace: newrelic
    version: 5.0.4
    values:
      - ./values/nri-bundle.yaml
      - {{ $secrets.newrelic | toYaml | nindent 8 }}

  - name: nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    namespace: kube-system
    version: 4.0.18
    values:
      - ./values/nfs-subdir-external-provisioner.yaml

  - chart: traefik/traefik
    name: traefik
    namespace: kube-system
    version: 21.2.0
    values:
      - ./values/traefik.yaml
