{{- range .Values.templates }}
---
{{- if typeIsLike "string" . }}
{{ tpl . $ }}
{{- else }}
{{ tpl (. | toYaml) $ }}
{{- end }}
{{- end }}

{{- range .Values.raw }}
---
{{- if typeIsLike "string" . }}
{{ . }}
{{- else }}
{{ . | toYaml }}
{{- end }}
{{- end }}
