helmDefaults:
  atomic: true
  cleanupOnFail: false
  createNamespace: true
  devel: false
  historyMax: 10
  skipDeps: true
  wait: true
  waitForJobs: true

repositories:
  - name: actions-runner-controller
    url: https://actions-runner-controller.github.io/actions-runner-controller
  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts/
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: flipt
    url: https://helm.flipt.io
  - name: huisheng
    url: git+https://github.com/hans-m-song/huisheng@charts?ref=master
  - name: jetstack
    url: https://charts.jetstack.io
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: minio
    url: https://charts.min.io/
  - name: newrelic
    url: https://helm-charts.newrelic.com
  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  - name: traefik
    url: https://helm.traefik.io/traefik
