{{- $secrets := readFile "./secrets.yaml" | fromYaml -}}

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.14.5
    labels:
      purpose: networking

  - name: cloudflare-tunnel
    chart: cloudflare/cloudflare-tunnel-remote
    namespace: kube-system
    version: 0.1.1
    labels:
      purpose: networking
    values:
      - replicaCount: 2
        image:
          tag: 2024.2.0
      - {{- $secrets.cloudflareTunnel | toYaml | nindent 8 }}

  - name: cluster-issuer
    chart: ./charts/cluster-issuers
    namespace: cert-manager
    labels:
      purpose: networking
    values:
      - {{- $secrets.clusterIssuers | toYaml | nindent 8 }}

  - name: external-dns-cloudflare-tunnel
    chart: external-dns/external-dns
    namespace: kube-system
    version: 1.14.4
    labels:
      purpose: networking
    values:
      - ./values/external-dns-cloudflare-tunnel.yaml
      - {{- $secrets.externalDnsCloudflareTunnel | toYaml | nindent 8 }}

  - name: external-dns-pihole
    chart: external-dns/external-dns
    namespace: kube-system
    version: 1.14.4
    labels:
      purpose: networking
    values:
      - ./values/external-dns-pihole.yaml
      - {{- $secrets.externalDnsPihole | toYaml | nindent 8 }}
  
  - name: nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    namespace: kube-system
    version: 4.0.18
    labels:
      purpose: networking
    values:
      - ./values/nfs-subdir-external-provisioner.yaml

  - name: traefik
    chart: traefik/traefik
    namespace: kube-system
    version: 25.0.0
    labels:
      purpose: networking
    values:
      - ./values/traefik.yaml
