{{- $secrets := readFile "./secrets.yaml" | fromYaml -}}

releases:
  - name: flipt
    chart: flipt/flipt
    namespace: flipt
    version: 0.52.0
    values:
      - ./values/flipt.yaml

  - name: home-assistant
    chart: ./charts/generic
    namespace: home-assistant
    values:
      - ./values/home-assistant.yaml

  - name: huisheng
    chart: huisheng/huisheng
    namespace: huisheng
    version: 0.0.5
    values:
      - ./values/huisheng.yaml
      - {{- $secrets.huisheng | toYaml | nindent 8 }}

  - name: minio
    chart: ./charts/generic
    namespace: minio
    labels:
      purpose: storage
    values:
      - ./values/minio.yaml
      - {{- $secrets.minio | toYaml | nindent 8 }}

  - name: mqtt
    chart: ./charts/generic
    namespace: mqtt
    values:
      - ./values/mqtt.yaml

  - name: redis
    chart: ./charts/generic
    namespace: redis
    values:
      - ./values/redis.yaml
      - {{- $secrets.redis | toYaml | nindent 8}}

  - name: zigbee2mqtt
    chart: ./charts/generic
    namespace: home-assistant
    values:
      - ./values/zigbee2mqtt.yaml
