deployment:
  strategy:
    type: Recreate
  nodeSelector:
    kubernetes.io/hostname: wheatley

containers:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.70.1
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
    volumes:
      data:
        mount:
          mountPath: /data
          readonly: false
        spec:
          hostPath:
            path: /mnt/data/nfs/k8s/monitoring/openobserve-data
    ports:
      http:
        protocol: TCP
        internalPort: 5080
        externalPort: 5080
      grpc:
        protocol: TCP
        internalPort: 5081
        externalPort: 5081
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 5080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    env:
      RUST_LOG: warn
      ZO_DATA_DIR: /data/
      ZO_TELEMETRY: "false"
      ZO_USAGE_ORG: default
      ZO_USAGE_REPORTING_ENABLED: "true"
      ZO_WEB_URL: https://o2.axatol.xyz
      ZO_DISK_CACHE_ENABLED: "false"

service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: o2.axatol.xyz
    external-dns.alpha.kubernetes.io/target: http://openobserve.monitoring.svc.cluster.local:5080
