{{ $secrets :=  readFile "./secrets.yaml" | fromYaml }}

helmDefaults:
  atomic: true
  cleanupOnFail: false
  createNamespace: true
  devel: false
  historyMax: 10
  skipDeps: true
  wait: true
  waitForJobs: true

repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: huisheng
    url: git+https://github.com/hans-m-song/huisheng@charts?ref=master
  - name: minio
    url: https://charts.min.io/
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.11.0

  - name: huisheng
    chart: huisheng/huisheng
    namespace: huisheng
    values:
      - ./values/huisheng.yaml
      - {{- $secrets.huisheng | toYaml | nindent 8 }}

  - name: metrics-server
    chart: metrics-server/metrics-server
    namespace: kube-system
    version: 3.8.4
    values:
      - ./values/metrics-server.yaml

  - name: minio
    chart: minio/minio
    namespace: minio
    version: 5.0.10
    values:
      - ./values/minio.yaml
      - {{- $secrets.minio | toYaml | nindent 8 }}

  # - name: minio
  #   chart: ./charts/minio
  #   namespace: minio
  #   values:
  #     - data:
  #         volumeMount:
  #           hostPath: /var/lib/skynet/data

  # - name: mongo
  #   chart: ./charts/mongo
  #   namespace: mongo

  # - name: mqtt`
  #   chart: ./charts/mqtt
  #   namespace: mqtt

  - chart: traefik/traefik
    name: traefik
    namespace: kube-system
    version: 21.2.0
    values:
      - ./values/traefik.yaml
