---
- name: Install base packages
  when: ansible_facts.os_family == 'Debian'
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - build-essential
    - ca-certificates
    - curl
    - fzf
    - git
    - gnupg
    - jq
    - nfs-common
    - ripgrep
    - rsync
    - samba
    - software-properties-common
