receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  filelog:
    include: [/var/lib/docker/containers/*/*-json.log]
    poll_interval: 200ms
    start_at: end
    include_file_name: false
    include_file_path: false
    operators:
      - id: container-parser
        type: container
        format: docker
        add_metadata_from_filepath: false

  docker_stats:
    collection_interval: 30s
    metrics:
      # default
      container.blockio.io_service_bytes_recursive:
        enabled: true
      container.cpu.usage.kernelmode:
        enabled: false
      container.cpu.usage.total:
        enabled: true
      container.cpu.usage.usermode:
        enabled: false
      container.cpu.utilization:
        enabled: true
      container.memory.file:
        enabled: false
      container.memory.percent:
        enabled: true
      container.memory.total_cache:
        enabled: false
      container.memory.usage.limit:
        enabled: false
      container.memory.usage.total:
        enabled: true
      container.network.io.usage.rx_bytes:
        enabled: true
      container.network.io.usage.rx_dropped:
        enabled: false
      container.network.io.usage.tx_bytes:
        enabled: true
      container.network.io.usage.tx_dropped:
        enabled: false
      # optional
      container.restarts:
        enabled: true
      container.uptime:
        enabled: true

  hostmetrics:
    root_path: /hostfs
    collection_interval: 60s
    scrapers:
      cpu: {}
      disk: {}
      load: {}
      filesystem: {}
      memory: {}
      network: {}
      paging: {}
      process:
        mute_process_exe_error: true
        mute_process_io_error: true
        mute_process_name_error: true
        mute_process_user_error: true
      processes: {}

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  resourcedetection/oraclecloud:
    detectors: [env, oraclecloud]
    timeout: 2s
    override: false
  resourcedetection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

exporters:
  otlphttp:
    endpoint: "{{ openobserve.otlp_http_endpoint }}"
    headers:
      Authorization: "{{ openobserve.authorization }}"
      organization: default
      stream-name: default
  debug:
    verbosity: normal

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp, filelog]
      processors: [batch]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp, docker_stats]
      processors: [batch]
      exporters: [otlphttp]
    metrics/internal:
      receivers: [hostmetrics]
      processors:
        [resourcedetection/oraclecloud, resourcedetection/docker, batch]
      exporters: [otlphttp]
