{{- if gt (len .Values.containers) 0 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "generic.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "generic.selectors" . | nindent 6 }}
  replicas: {{ .Values.deployment.replicas }}
  strategy: {{ .Values.deployment.strategy | toYaml | nindent 4 }}
  template:
    metadata:
      labels: {{- include "generic.selectors" . | nindent 8 }}
      annotations:
        checksum/config: {{ include "generic.configChecksum" . }}
    spec:
      {{- $volumes := dict }}
      {{- range $container := .Values.containers }}
      {{- $containerVolumes := $container.volumes | default (dict) }}
      {{- $volumes = merge $volumes $containerVolumes }}
      {{- end }}
      {{- if gt (len .Values.files) 0 }}
      {{- $volumes = set $volumes "files" (dict 
        "spec" (dict
          "configMap" (dict
            "name" (print $.Release.Name "-files")
          )
        )
      )}}
      {{- end }}
      {{- if gt (len $volumes) 0 }}
      volumes:
      {{- range $name, $volume := $volumes }}
      - name: {{ $name }}
        {{- $volume.spec | toYaml | nindent 8 }}
      {{- end }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      serviceAccountName: {{ default .Release.Name .Values.rbac.serviceAccountName }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector: {{ .Values.deployment.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
      {{- range $name, $container := .Values.initContainers }}
      {{- $ctx := dict "root" $ "name" $name "container" $container }}
      - {{- include "generic.container" $ctx | trim | nindent 8 -}}
      {{- end }}
      {{- end }}
      containers:
      {{- range $name, $container := .Values.containers }}
      {{- $ctx := dict "root" $ "name" $name "container" $container }}
      - {{- include "generic.container" $ctx | trim | nindent 8 -}}
      {{- end }}
{{- end }}
