{{- if gt (len .Values.ingress.hosts) 0}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "generic.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}

  rules:
  {{- range $name, $host := .Values.ingress.hosts }}
  - host: {{ $name }}
    http:
      paths:
      {{- range $spec := $host }}
      - path: {{ $spec.path }}
        pathType: {{ default "Prefix" $spec.pathType }}
        backend:
          service:
            name: {{ $.Release.Name }}
            port:
              {{- if $spec.portNumber }}
              number: {{ $spec.portNumber }}
              {{- else }}
              name: {{ $spec.portName }}
              {{- end }}
      {{- end }}
  {{- end }}

  {{- $tls := dict }}
  {{- range $name, $host := .Values.ingress.hosts }}
  {{- range $spec := $host }}
  {{- if or $spec.tls $spec.tlsSecretName }}
  {{- $defaultTlsSecretName := $name | replace "." "-" | printf "%s-tls" }}
  {{- $tls = set $tls $name (default $defaultTlsSecretName $spec.tlsSecretName) }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if gt (len $tls) 0 }}
  tls:
  {{- range $host, $secretName := $tls }}
  - hosts:
    - {{ $host }}
    secretName: {{ $secretName }}
  {{- end }}
  {{- end }}
{{- end }}
