---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: module-cache
  namespace: actions-runner-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-persistent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tool-cache
  namespace: actions-runner-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-persistent
