---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  ports:
    - name: traefik
      port: 9000
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  ingressClassName: traefik
  rules:
    - host: traefik.k8s.axatol.xyz
      http:
        paths:
          - backend:
              service:
                name: traefik-dashboard
                port:
                  number: 9000
            path: /
            pathType: Prefix
