{{- if and .Values.ingress.create (or .Values.ingress.consoleHost .Values.ingress.apiHost) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "minio.labels" . | nindent 4 }}
  annotations: {{- .Values.ingress.annotations | toYaml | nindent 4 }}
spec:
  {{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.ingressClass }}
  {{- end }}
  rules:
  {{- if .Values.ingress.consoleHost }}
  - host: {{ .Values.ingress.consoleHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              name: console
  {{- end }}
  {{- if .Values.ingress.apiHost }}
  - host: {{ .Values.ingress.apiHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              name: api
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls: {{ .Values.ingress.tls | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
