{{- if or .Values.service.create .Values.ingress.create -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.namespace }}
  labels: {{- include "minio.labels" . | nindent 4 }}
spec:
  selector: {{- include "minio.selectors" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: api
      targetPort: api
      port: {{ .Values.service.apiPort }}
      protocol: TCP
    - name: console
      targetPort: console
      port: {{ .Values.service.consolePort }}
      protocol: TCP
{{- end -}}
