---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arc-hans-m-song-iac
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arc-hans-m-song-iac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "edit"
subjects:
  - kind: ServiceAccount
    name: arc-hans-m-song-iac
    namespace: actions-runner-system
