---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-ephemeral
provisioner: cluster.local/nfs-subdir-external-provisioner
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  archiveOnDelete: "false"
  onDelete: delete
  pathPattern: ${.PVC.namespace}/${.PVC.name}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-persistent
provisioner: cluster.local/nfs-subdir-external-provisioner
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  archiveOnDelete: "false"
  onDelete: retain
  pathPattern: ${.PVC.namespace}/${.PVC.name}
