---
- name: Configure containers
  hosts: grady
  become: true
  gather_facts: true
  tasks:
    - name: Docker shared network
      community.docker.docker_network:
        name: proxy
        driver: bridge

    - name: Deploy grady docker compose stack
      ansible.builtin.import_role:
        name: docker_compose_stack
      vars:
        docker_compose_stack_project: grady
        docker_compose_stack_src: "{{ playbook_dir }}/files"
        docker_compose_stack_remove_orphans: true
        docker_compose_stack_restart_map:
          traefik/static.yaml: traefik
          crowdsec/: crowdsec
          otel-collector/default.yaml: otel-collector
          otel-collector/buildsight.yaml: buildsight-otel-collector
