---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "mongo.labels" . | nindent 4 }}
spec:
  selector: {{- include "mongo.selectors" . | nindent 6 }}
  type: ClusterIP
  ports:
  - name: api
    port: {{ .Values.service.port }}
    targetPort: 27017
  - name: web
    port: {{ .Values.service.webPort }}
    targetPort: 8081