name: Get Terraform Variables
description: Get Terraform Variables

runs:
  using: composite

  steps:
    - name: Get auth0_domain
      uses: axatol/actions/get-ssm-parameter@release
      with:
        path: /infrastructure/auth0/domain
        env-name: TF_VAR_auth0_domain

    - name: Get auth0_client_id
      uses: axatol/actions/get-ssm-parameter@release
      with:
        path: /infrastructure/terraform/auth0_client_id
        env-name: TF_VAR_auth0_client_id

    - name: Get auth0_client_secret
      uses: axatol/actions/get-ssm-parameter@release
      with:
        path: /infrastructure/terraform/auth0_client_secret
        env-name: TF_VAR_auth0_client_secret

    - name: Get github_token
      uses: axatol/actions/get-ssm-parameter@release
      with:
        path: /infrastructure/terraform/github_token
        env-name: TF_VAR_github_token

    - name: Get new_relic_account_id
      uses: axatol/actions/get-ssm-parameter@release
      with:
        path: /infrastructure/new_relic/account_id
        env-name: TF_VAR_new_relic_account_id

    - name: Get new_relic_api_key
      uses: axatol/actions/get-ssm-parameter@release
      with:
        path: /infrastructure/terraform/new_relic_api_key
        env-name: TF_VAR_new_relic_api_key

    - name: Get octopus_deploy_api_key
      uses: axatol/actions/get-ssm-parameter@release
      with:
        path: /infrastructure/terraform/octopus_deploy_api_key
        env-name: TF_VAR_octopus_deploy_api_key
