---
- name: Check Zerotier GPG key
  ansible.builtin.stat:
    path: /etc/apt/keyrings/zerotier.asc
  register: gpg_key_exists

- name: Add ZeroTier GPG apt key
  ansible.builtin.get_url:
    url: https://download.zerotier.com/contact@zerotier.com.gpg
    dest: /etc/apt/keyrings/zerotier.asc
    owner: root
    group: root
    mode: "0644"
  when: not gpg_key_exists.stat.exists

- name: Add ZeroTier repository
  ansible.builtin.apt_repository:
    repo: >-
      deb
      [arch=amd64 signed-by=/etc/apt/keyrings/zerotier.asc]
      http://download.zerotier.com/debian/{{ ansible_facts.distribution_release }}
      {{ ansible_facts.distribution_release }}
      main
    state: present
    update_cache: true

- name: Install zerotier-one
  ansible.builtin.apt:
    name: zerotier-one
    state: present

- name: Start zerotier-one
  ansible.builtin.systemd:
    name: zerotier-one
    state: started
    enabled: true

- name: Join ZeroTier network
  ansible.builtin.command:
    cmd: "zerotier-cli join {{ zerotier_client_network_id }}"
    creates: "/var/lib/zerotier-one/networks.d/{{ zerotier_client_network_id }}.conf"
  when: zerotier_client_network_id is defined and zerotier_client_network_id != ""

- name: Read ZeroTier client identity
  ansible.builtin.slurp:
    path: /var/lib/zerotier-one/identity.public
  register: zerotier_identity

- name: Output ZeroTier client identity
  ansible.builtin.debug:
    msg: "{%- set raw = zerotier_identity.content | b64decode %}{{- raw.split(':')[0] | trim }}"
