---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: {{ .Release.namespace }}
  labels: {{- include "mssql.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "mssql.selectors" . | nindent 6 }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {{- include "mssql.selectors" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 10001
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: {{ .Values.storage.name }}
      containers:
        - name: mssql
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
            - name: MSSQL_PID
              value: Express
            - name: ACCEPT_EULA
              value: "Y"
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
