{{- if .Values.service.create -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.namespace }}
  labels: {{- include "mssql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector: {{- include "mssql.selectors" . | nindent 4 }}
{{- end -}}
