---
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}/gpg"
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_facts.distribution | lower }} {{ ansible_facts.distribution_release }} stable"
    state: present
    update_cache: true

- name: Install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present
