atlas:
  hosts:
    atlas.siamese-halibut.ts.net:

wheatley:
  hosts:
    wheatley.siamese-halibut.ts.net:

glados:
  hosts:
    glados.siamese-halibut.ts.net:

pbody:
  hosts:
    pbody.siamese-halibut.ts.net:

grady:
  hosts:
    grady.siamese-halibut.ts.net:
      ansible_user: ubuntu

vps:
  children:
    grady:

lan:
  children:
    atlas:
    wheatley:
    glados:

servers:
  children:
    atlas:
    wheatley:
    glados:
    grady:
