deployment:
  strategy:
    type: Recreate
  nodeSelector:
    k8s.axatol.xyz/supports-zigbee: "true"

containers:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    resources:
      limits:
        cpu: 400m
        memory: 512Mi
    env:
      TZ: Australia/Brisbane
    ports:
      console:
        protocol: TCP
        internalPort: 8080
        externalPort: 8080
    # required to mount the usb dongle
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      runAsUser: 0
      runAsGroup: 0
    volumes:
      data:
        mount:
          mountPath: /app/data
          readOnly: false
        spec:
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
      zigbee-dongle:
        mount:
          mountPath: /dev/ttyACM0
          readOnly: false
        spec:
          hostPath:
            path: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220818083418-if00
            type: ""
      device-discovery:
        mount:
          mountPath: /run/udev
          readOnly: true
        spec:
          hostPath:
            path: /run/udev
            type: ""
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10

ingress:
  ingressClassName: traefik
  hosts:
    zigbee2mqtt.lab.axatol.local:
      - path: /
        portName: console

pvc:
  zigbee2mqtt-data:
    storageClassName: nfs-csi-persistent
    capacity: 1Gi
