---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- include "octopus-deploy-worker.labels" . | nindent 4 }}
type: Opaque
data:
  ServerApiKey: {{ .Values.octopus.serverApiKey | b64enc }}
