apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "octopus-deploy-worker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "octopus-deploy-worker.selectors" . | nindent 6 }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels: {{- include "octopus-deploy-worker.selectors" . | nindent 8 }}
    spec:
      containers:
      - name: worker
        image: {{ .Values.image }}
        imagePullPolicy: Always
        serviceAccountName: {{ default .Release.Name .Values.rbac.serviceAccountName }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config
        - secretRef:
            name: {{ .Release.Name }}-secrets
        volumeMounts:
        - name: prestop-script
          mountPath: /usr/local/bin/prestop.sh
          subPath: prestop.sh
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /usr/local/bin/prestop.sh
      volumes:
      - name: prestop-script
        configMap:
          name: {{ .Release.Name }}-prestop-script
          defaultMode: 0755
