name: ECR Private Publish

on:
  workflow_call:
    inputs:
      repository:
        description: Repository name
        required: true
        type: string

      context:
        description: Directory for build context
        required: true
        type: string

      region:
        description: AWS region
        required: false
        type: string
        default: ap-southeast-2

    secrets:
      AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN:
        required: true
      AWS_ACCOUNT_ID:
        required: true

env:
  IMAGE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ inputs.repository }}

jobs:
  publish:
    runs-on:
      - ${{ github.repository_owner }}-${{ github.event.repository.name }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: axatol/actions/assume-aws-role@release
        with:
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}

      - uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private
          registries: ${{ secrets.AWS_ACCOUNT_ID }}
          mask-password: true

      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: axatol/actions/docker-build-push@release
        with:
          image: ${{ env.IMAGE }}
          build-context: ${{ inputs.context }}
          use-cache: false
          tag-previous: false
