name: Deploy Github

on:
  push:
    branches:
      - master
    paths:
      - "github/**/*.tf"
      - .github/workflows/deploy-github.yaml
      - .github/workflows/_terraform.yaml

  pull_request:
    paths:
      - "github/**/*.tf"
      - .github/workflows/deploy-github.yaml
      - .github/workflows/_terraform.yaml

permissions:
  pull-requests: write

jobs:
  terraform:
    name: Terraform

    uses: ./.github/workflows/_terraform.yaml
    with:
      workspace: github

    secrets:
      TERRAFORM_TOKEN: ${{ secrets.TERRAFORM_TOKEN }}
