name: Terraform Auth0

on:
  push:
    branches:
      - master
    paths:
      - "auth0/**/*.tf"
      - .github/workflows/terraform-auth0.yaml

  pull_request:
    paths:
      - "auth0/**/*.tf"
      - .github/workflows/terraform-auth0.yaml

permissions:
  pull-requests: write

jobs:
  terraform:
    name: Terraform

    uses: ./.github/workflows/_terraform.yaml
    with:
      workspace: auth0

    secrets:
      TERRAFORM_TOKEN: ${{ secrets.TERRAFORM_TOKEN }}
